### PR TITLE
HistogramEqualizaion

### PR DESCRIPTION
**Pull request by Black-Lights**
Completed HistogramEqualizaion with example and test.

### CODE REVIEW

**Review by Black-Lights — COMMENTED** [review]
Everything s fine

**Comment by erfaneshghelahi** [comment]
good everything is fine

**Review by erfaneshghelahi — COMMENTED** [review]
good

**Review by Black-Lights — COMMENTED** [review]
its good

**Review by Black-Lights — COMMENTED** [review]
every thing is good

**Review by erfaneshghelahi — APPROVED** [review]
good

**Pull request merged**
